version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: blog_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpassword
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
